require File.dirname(__FILE__) + '/../spec_helper'

# describe LvmBackup, "parsing" do
#   before(:all) do
#     @parser = LvmBackupParser.new
#   end
#   describe "multiline input" do
#     before(:all) do
#       @result = @parser.parse("foo = 42\n\nbar = 43\nbaz { i = 0 }\n# end config\n")
#     end
#     it "shouldn't be nil" do
#       @result.should_not be_nil
#     end
#     it "should return a kind of LvmBackup::AssignemtnOperation" do
#       @result.should be_a_kind_of(LvmBackup::FileContents)
#     end
# 
#     describe "evaluated output" do
#       before(:all) do
#         @evaluated_result = @result.eval({})
#       end
#       it "should return a hash of the evaluated string" do
#         @evaluated_result.should be_a_kind_of(Hash)          
#       end
#       it "should be able to lookup the variable name" do
#         @evaluated_result['foo'].should eql('42')          
#       end
#       it "should be able to lookup the variable name" do
#         @evaluated_result['bar'].should eql('43')          
#       end
#       it "should be able to lookup the variable name" do
#         @evaluated_result['baz']['i'].should eql('0')          
#       end
#     end
#   end
# end

describe LvmBackup, "parsing" do
  before(:all) do
    @parser = LvmBackupParser.new
  end
  describe "multiline input" do
# Generated by LVM2: Thu May  1 21:01:17 2008\n\ncontents = \"Text Format Volume Group\"\nversion = 1\n"    
    before(:all) do
      str =<<-EOF
# Generated by LVM2: Thu May  1 21:01:17 2008

contents = "Text Format Volume Group"
version = 1

ey04-data00 { 
  id = 4
  version = 1234
  physical_volumes {

		pv0 {
			id = "eIctnq-lQsq-xkLb-w7yj-4m0U-kXeS-xY9qzo"
			device = "/dev/etherd/e0.0p15"	# Hint only

			status = ["ALLOCATABLE"]
			tags = ["eyinternal", "build"]
			dev_size = 468648117	# 223.469 Gigabytes
			pe_start = 384
			pe_count = 57207	# 223.465 Gigabytes
		}
		pv1 {
			id = "TEt3bz-id4I-fIfc-PeE0-IBvS-651d-DrDabH"
			device = "/dev/etherd/e0.1"	# Hint only

			status = ["ALLOCATABLE"]
			dev_size = 1953546237	# 931.523 Gigabytes
			pe_start = 384
			pe_count = 238469	# 931.52 Gigabytes
		}
	}
}
EOF
      @result = @parser.parse(str)
      # pp @parser
    end
    it "shouldn't be nil" do
      @result.should_not be_nil
    end
    
    it "should return a kind of LvmBackup::FileContents" do
      @result.should be_a_kind_of(LvmBackup::FileContents)
    end

    describe "evaluated output" do
      before(:all) do
        @evaluated_result = @result.eval({})
      end
      it "should return a hash of the evaluated string" do
        @evaluated_result.should be_a_kind_of(Hash)          
      end
      it "should be able to lookup the variable named version" do
        @evaluated_result['version'].should eql(1)          
      end
      it "should be able to lookup the variable named contents" do
        @evaluated_result['contents'].should eql('Text Format Volume Group')
      end
    end
  end
end
